<template>
  <div v-if="allLoaded" class="invoice_detail_container">

    <div class="invoice_information">

      <div class="invoice_logo_header"> 
        
        <div class="invoice_number_date">
          <h1>Invoice #{{ invoiceDetails.id }}</h1>
          <p>
              Payment method: {{ invoiceDetails.paymentMethod }} <br>
              Invoice generated by: {{ invoiceDetails.createdByUser }} <br>
              Invoice date: {{ invoiceDate.day }}/{{invoiceDate.month}}/{{invoiceDate.year}} <br>
          </p>
        </div>
        <img :src="imageLogoInvoice" alt="No photo available">

      </div>

      <div class="invoice_details_header">
        <div class="invoice_content_container">
          <p>
            <b>COMPANY INFORMATION</b> <br>
            Supply Chain Solutions <br>
            Grand Rapids, Michigan <br>
            4607 44th Street S.E. <br>
            Grand Rapids, MI 49512  <br>
            Phone: (+1) 616.541.3706 <br>
            tms@scsolutionsinc.com <br><br>
          </p>
        </div>

        <div class="invoice_details_client_container">
        <h3></h3>
        <p>
          <b>BILL TO: {{ (invoiceDetails.idClient.name).toUpperCase() }}</b> <br>
          Company ID: {{ invoiceDetails.idClient.cc }} <br>
          Address: {{ invoiceDetails.idClient.address }} <br>
          Phone: {{ invoiceDetails.idClient.phone }} <br>
          Email: {{ invoiceDetails.idClient.email }} <br>
          Country: {{ invoiceDetails.idClient.country }} <br>
          Contact name: {{ invoiceDetails.idClient.contactName }} <br>
        </p>
        </div>
      </div>

      <div class="invoice_details_product_container_table">
        <table>
          <tr>
            <th>N°</th>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Tax Percentage</th>
            <th>Total</th>
          </tr>
          <tr v-for="(product, index) in productsList" :key="product.id">
            <td>{{index+1}}</td>
            <td>{{ product.name }}</td>
            <td class="invoice_details_table_number_align">${{ (product.unitPrice).toFixed(2) }}</td>
            <td>{{ product.quantity }} Und</td>
            <td>{{ product.taxPercentage }}%</td>
            <td class="invoice_details_table_number_align">${{ (product.subTotalValue).toFixed(2) }}</td>
          </tr>
          <tr>
            <td colspan="5"> 
              <p><b> Invoice Total:</b></p> 
              </td>
            <td> 
              <p class="invoice_details_table_number_align"><b>${{ (invoiceDetails.totalValue).toFixed(2) }}</b></p> 
              </td>
          </tr>
        </table>

        <div class="invoice_details_action_buttons">
          <button v-on:click="processInvoiceDelete(invoiceDetails.id)">🗑</button>
        </div>
      </div>

      <div class="invoice_company_details_terms_contitions">
        <p>
          <b>TERMS & CONDITIONS</b> <br>
          Payment of invoices is paid at the moment the invoice is generated. <br>
          Payment due date may be subject to late fees or extra charges.  <br>
          <br>Thank you for your business.
        </p>
      </div>

    </div>
 

    
  </div>


</template>

<script>
import axios from "axios";
import imageLogo from "../assets/SCS-Logo.png";

export default {
  name: "InvoiceDetails",
  data: function () {
    return {
      allLoaded: false,
      invoiceDetails: {},
      productsList: [],
      invoiceDate: {
          day: "",
          month: "",
          year: "",
      },
      imageLogoInvoice: imageLogo,
    };
  },

  methods: {
    processInvoiceDetails: async function () {
      if (
        localStorage.getItem("token_access") === null ||
        localStorage.getItem("token_refresh") === null
      ) {
        this.$emit("logOut");
        return;
      }
      await this.verifyToken();

      let token = localStorage.getItem("token_access");
      let invoiceID = localStorage.getItem("invoiceId");

      axios
        .get(`http://127.0.0.1:8000/invoice/${invoiceID}/`, {
          headers: { Authorization: `Bearer ${token}` },
        })
        .then((result) => {
          this.invoiceDetails = result.data;
          this.productsList = result.data.products;
          let date = new Date(result.data.date);
          this.invoiceDate.day = date.getDate();
          this.invoiceDate.month = date.getMonth()+1;
          this.invoiceDate.year = date.getFullYear();
          this.allLoaded = true;
        })
        .catch((error) => {
          console.log(error);
          this.$emit("logOut");
        });
    },

    processInvoiceDelete: async function(invoiceElementId){
      if (
        localStorage.getItem("token_access") === null ||
        localStorage.getItem("token_refresh") === null
      ) {
        this.$emit("logOut");
        return;
      }
      await this.verifyToken();

      let token = localStorage.getItem("token_access");
      localStorage.setItem("invoiceId", invoiceElementId);
      let invoice_id = localStorage.getItem("invoiceId");
      
      axios
        .get(`http://127.0.0.1:8000/invoice/delete/${invoice_id}/`, {
          headers: { Authorization: `Bearer ${token}`}
        })
        .then((result) => {
          alert("Invoice deleted");
          this.$router.push({ name: "invoice" });
        })
        .catch((error) => {
          console.log(error);
          this.$$emit("logOut");
        });
    },

    verifyToken: function () {
      return axios
        .post(
          "http://127.0.0.1:8000/refresh/",
          { refresh: localStorage.getItem("token_refresh") },
          { headers: {} }
        )
        .then((result) => {
          localStorage.setItem("token_access", result.data.access);
        })
        .catch(() => {
          this.$emit("logOut");
        });
    },
  },
  created: async function () {
    this.processInvoiceDetails();
  },
};
</script>


<style>

.invoice_detail_container{
  display: flex;
  flex-direction: column;
  align-items: center;
}

.invoice_information {
  width: 60%;
  padding: 3%;
  display: flex;
  flex-direction: column;
  align-items: center;
  box-shadow: 3px 3px 3px 3px grey; 
}

.invoice_logo_header img{
  width: 50%;
  height: 100%;
}

.invoice_logo_header{
  display: flex;
  justify-content: space-between;
  width: 80%;
  align-items: center;
}

.invoice_details_header{
  display: flex;
  justify-content: space-between;
  width: 80%;
}

.invoice_number_date{
  margin: 0 0 0 3%;
}

.invoice_content_container{
  margin: 3%;
}

.invoice_details_client_container{
  margin: 3%;
}

.invoice_details_product_container_table{
  width: 80%;
  display: flex;
  flex-direction: column;
  justify-content: center;
}


.invoice_details_product_container_table tr:nth-child(odd) {background-color: #D9E1F2;}
.invoice_details_product_container_table tr:nth-child(even) {background-color: #FFFFFF;}

.invoice_details_product_container_table table,
.invoice_details_product_container_table th,
.invoice_details_product_container_table td {
  border: 1px solid black;
  border-collapse: collapse;
  min-width: 60px;
}

.invoice_details_product_container_table table {
  width: 100%;
  empty-cells: hide;
  text-align: center;
}

.invoice_details_table_number_align{
  text-align: right;
}

.invoice_details_product_container_table p {
  font-size: 20px;
  margin: 5px;
}



.invoice_details_action_buttons{
  display: flex;
  justify-content: flex-end;
}

.invoice_details_action_buttons button {
  color: white;
  background: #565189;
  border: 1px solid white;
  width: 50px;
  border-radius: 50px;
  font-size: 25px;
  margin: 1%;
}

.invoice_details_action_buttons button:hover {
  color: #e5e7e9;
  background: #031742;
  border: 1px solid white;
}

.invoice_company_details_terms_contitions{
  width: 75%;
  display: flex;
  flex-direction: column;
  justify-content: center;
}


</style>

